version: '{branch}-{build}'
environment:
  PY_PYTHON: 3.7-32
install:
- cmd: >-
    set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

    python -m pip install -U pip

    pip install wheel
    
    pip install scons

    pip install markdown
build_script:
- cmd: scons
artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
before_deploy:
- ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)

deploy:
- provider: Environment
  name: github_deployment
  on:
    APPVEYOR_REPO_TAG: true
